auth_enabled: true

server:
  http_listen_port: 3100
  log_level: info

ingester:
  chunk_idle_period: 3m
  max_chunk_age: 1h
  chunk_retain_period: 1m
  max_streams_per_user: 10000
  chunk_encoding: snappy

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 128
  ingestion_burst_size_mb: 256

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: s3
  s3:
    s3: s3://minioadmin:Minio.OddoBhf@Secure123@minio:9000/loki
    insecure: true
    skip_credentials_validation: true

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

query_config:
  max_cache_freshness_per_query: 10m
  engine: prometheus