# ============================================
# Alertmanager Configuration - Training Stack
# Data2AI Academy
# ============================================

global:
  resolve_timeout: 5m
  # SMTP Configuration (for email alerts)
  # smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_from: 'grafana@data2ai.academy'
  # smtp_auth_username: 'your-email@gmail.com'
  # smtp_auth_password: 'your-app-password'
  # smtp_require_tls: true

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alerts
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 1h
    
    # Info alerts
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 1m
      repeat_interval: 4h

# Inhibition rules
inhibit_rules:
  # Inhibit warning if critical is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

# Receivers (notification channels)
receivers:
  # Default receiver
  - name: 'default'
    # webhook_configs:
    #   - url: 'http://localhost:5001/webhook'

  # Critical alerts receiver
  - name: 'critical-alerts'
    # Email notifications
    # email_configs:
    #   - to: 'oncall@data2ai.academy'
    #     headers:
    #       Subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
    
    # Slack notifications
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#critical-alerts'
    #     title: 'Critical Alert: {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  # Warning alerts receiver
  - name: 'warning-alerts'
    # email_configs:
    #   - to: 'team@data2ai.academy'
    #     headers:
    #       Subject: '[WARNING] {{ .GroupLabels.alertname }}'

  # Info alerts receiver
  - name: 'info-alerts'
    # webhook_configs:
    #   - url: 'http://localhost:5001/info-webhook'
