# =============================================
# Grafana Data Source: MS SQL Server
# E-Banking Financial Observability
# =============================================

apiVersion: 1

datasources:
  - name: MS SQL Server - E-Banking
    type: mssql
    access: proxy
    url: mssql:1433
    database: EBankingDB
    user: sa
    secureJsonData:
      password: ${MSSQL_SA_PASSWORD:-EBanking@Secure123!}
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      encrypt: 'false'
      sslmode: 'disable'
    editable: true
    isDefault: false
    version: 1
    uid: mssql_ebanking
