server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'

  # E-Banking Services logs
  - job_name: ebanking
    static_configs:
      - targets:
          - localhost
        labels:
          job: ebanking
          __path__: /logs/ebanking/*.log
          service: ebanking-platform

  # Auth Service logs
  - job_name: auth-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-service
          service: auth
          __path__: /logs/auth/*.log

  # Transaction Service logs
  - job_name: transaction-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: transaction-service
          service: transaction
          __path__: /logs/transaction/*.log

  # KPI Service logs
  - job_name: kpi-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: kpi-service
          service: kpi
          __path__: /logs/kpi/*.log