# Grafana Alert Rules Configuration
# This file provisions sample alert rules

apiVersion: 1

groups:
  # Prometheus Monitoring Alerts
  - orgId: 1
    name: prometheus-alerts
    folder: Observability
    interval: 1m
    rules:
      # Alert when Prometheus is down
      - uid: prometheus-down
        title: Prometheus is Down
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job="prometheus"} == 0
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations:
          summary: Prometheus instance is down
          description: "Prometheus has been down for more than 2 minutes"
        labels:
          severity: critical
          service: prometheus

      # Alert when any service is down
      - uid: service-down
        title: Service Down
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up == 0
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute"
        labels:
          severity: critical
          service: "{{ $labels.job }}"

  # System Resource Alerts
  - orgId: 1
    name: system-alerts
    folder: Observability
    interval: 1m
    rules:
      # High CPU Usage
      - uid: high-cpu
        title: High CPU Usage
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: High CPU usage detected
          description: "CPU usage is above 80% on {{ $labels.instance }} (current value: {{ $value }}%)"
        labels:
          severity: warning
          service: system

      # High Memory Usage
      - uid: high-memory
        title: High Memory Usage
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: High memory usage detected
          description: "Memory usage is above 85% on {{ $labels.instance }} (current value: {{ $value }}%)"
        labels:
          severity: warning
          service: system

      # Disk Space Low
      - uid: disk-space-low
        title: Disk Space Low
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"} / node_filesystem_size_bytes)) * 100 > 85
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: Disk space is running low
          description: "Disk usage is above 85% on {{ $labels.instance }} at {{ $labels.mountpoint }} (current value: {{ $value }}%)"
        labels:
          severity: warning
          service: system

  # Application Alerts
  - orgId: 1
    name: application-alerts
    folder: Observability
    interval: 1m
    rules:
      # High Error Rate
      - uid: high-error-rate
        title: High Error Rate
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations:
          summary: High error rate detected
          description: "Error rate is above 5% for {{ $labels.job }} (current value: {{ $value }})"
        labels:
          severity: critical
          service: "{{ $labels.job }}"

      # Slow Response Time
      - uid: slow-response
        title: Slow Response Time
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: Slow response time detected
          description: "95th percentile response time is above 1s for {{ $labels.job }} (current value: {{ $value }}s)"
        labels:
          severity: warning
          service: "{{ $labels.job }}"

  # Database Alerts
  - orgId: 1
    name: database-alerts
    folder: Observability
    interval: 1m
    rules:
      # MySQL Down
      - uid: mysql-down
        title: MySQL is Down
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job="mysql"} == 0
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: MySQL database is down
          description: "MySQL has been down for more than 1 minute"
        labels:
          severity: critical
          service: mysql

      # InfluxDB Down
      - uid: influxdb-down
        title: InfluxDB is Down
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job="influxdb"} == 0
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: InfluxDB is down
          description: "InfluxDB has been down for more than 1 minute"
        labels:
          severity: critical
          service: influxdb
