# Grafana Contact Points Configuration
# This file provisions notification channels for Grafana Alerting

apiVersion: 1

contactPoints:
  # Slack Contact Point
  - orgId: 1
    name: slack-notifications
    receivers:
      - uid: slack-receiver
        type: slack
        settings:
          # Slack webhook for PayementService app (BHF-ODDO-Grafana workspace)
          # IMPORTANT: Replace with your actual webhook URL before deploying
          # Get from: https://api.slack.com/apps/A09MQ4WMJVA/incoming-webhooks
          # NOTE: When using webhooks, do NOT specify 'recipient' or 'token'
          # The channel is configured in the webhook URL itself
          url: ${SLACK_WEBHOOK_URL:-https://hooks.slack.com/services/YOUR/WEBHOOK/URL}
          # Optional: Customize the message
          title: "{{ .CommonLabels.alertname }}"
          text: |
            {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Status:* {{ .Status }}
            *Severity:* {{ .Labels.severity }}
            *Summary:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            {{ end }}
          # Optional: Username and icon
          username: Grafana Observability
          icon_emoji: ":grafana:"
        disableResolveMessage: false

  # Email Contact Point (Gmail)
  - orgId: 1
    name: email-notifications
    receivers:
      - uid: email-receiver
        type: email
        settings:
          # Comma-separated list of email addresses
          addresses: recipient1@example.com;recipient2@example.com
          singleEmail: false
        disableResolveMessage: false

  # Combined Contact Point (Both Slack and Email)
  - orgId: 1
    name: critical-alerts
    receivers:
      - uid: critical-slack
        type: slack
        settings:
          # NOTE: When using webhooks, do NOT specify 'recipient' or 'token'
          url: ${SLACK_WEBHOOK_URL:-https://hooks.slack.com/services/YOUR/WEBHOOK/URL}
          title: "🚨 CRITICAL: {{ .CommonLabels.alertname }}"
          text: |
            *CRITICAL ALERT*
            {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Status:* {{ .Status }}
            *Severity:* {{ .Labels.severity }}
            *Instance:* {{ .Labels.instance }}
            *Summary:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Started:* {{ .StartsAt }}
            {{ end }}
          username: Grafana Critical Alerts
          icon_emoji: ":rotating_light:"
      - uid: critical-email
        type: email
        settings:
          addresses: admin@example.com;oncall@example.com
          singleEmail: false
